### ISSUE TITLE
How to train the model on a single class of Shapenet Data?

### ISSUE THREAD

**Issue by nitish11** [autonomousvision/differentiable_volumetric_rendering#14]
If I want to retrain the model on a single class of Shapenet Data, what are the variables to be changed in the configuration file? 
What is the use of pointcloud chamfer file mentioned in the config file? 
https://github.com/autonomousvision/differentiable_volumetric_rendering/blob/master/configs/default.yaml#L10

**Comment by m-niemeyer** [comment]
Hi @nitish11 , thanks a lot for your interest in our project!

**Single Class Training:**
You can train on a single class of the ShapNet dataset by adjusting the[ data - classes](https://github.com/autonomousvision/differentiable_volumetric_rendering/blob/master/configs/default.yaml#L5) argument in your config. For example, if you only want to train on cars which is the class "02958343", you have to set
```
data:
  classes: ['02958343']
```

**What is the Pointcloud Chamfer file?**
For evaluating our and baseline methods, we report the Chamfer distance. The pointcloud chamfer file entry in the config defines the name of the file containing the ground truth points which can be found in the respective model folder. We load [the respective field with this name as an argument](https://github.com/autonomousvision/differentiable_volumetric_rendering/blob/master/eval_meshes.py#L32) for evaluation.

**Comment by nitish11** [comment]
Hi @m-niemeyer, thanks fro your reply and clarifying the doubt. 

I want to train a model on only one class,; i.e; speaker - 03691459 . Before downloading the data using your [script](https://github.com/autonomousvision/differentiable_volumetric_rendering/blob/master/scripts/download_dataset.sh#L20
),  I just wanted to confirm if Kato shapenet data contains Speaker class or not. Could you please confirm.

**Comment by m-niemeyer** [comment]
@nitish11 yes, both ShapeNet datasets (Kato renderings and Choy renderings) contain the speaker class.

**Comment by nitish11** [comment]
@m-niemeyer : Thanks for the confirmation, I downloaded the NMR_dataset. And copied only one folder 03691459.  I modified config/default.yaml as mentioned below.
```
method: dvr
data:
  dataset_name: Shapes3D
  path: data/ShapeNet
  classes: ['03691459']
  input_type: image
  dim: 3
  n_views: 0
  n_views_input: 0
  pointcloud_chamfer_file: pointcloud.npz
  depth_folder: depth
  img_folder: image
  visual_hull_depth_folder: visual_hull_depth
  mask_folder: mask
  img_extension: png
  img_extension_input: jpg
  depth_extension: exr
  mask_extension: png
  img_size: null
``` 

**What is the use of  "img_folder_input"?**
https://github.com/autonomousvision/differentiable_volumetric_rendering/blob/master/configs/default.yaml#L13 ? 

I am getting the error `Error occurred when loading field inputs of model c3233311a94b7b968a0181490cb73cbc (03691459)`, the variables that are fetched [at this point ](https://github.com/autonomousvision/differentiable_volumetric_rendering/blob/master/im2mesh/data/fields.py#L257) are as follows
```
extension: jpg
folder: data/ShapeNet/03691459/c3233311a94b7b968a0181490cb73cbc/img_choy2016
files: []

``` 

The dataset contains 
```
$ ls data/ShapeNet/03691459/c3233311a94b7b968a0181490cb73cbc
image mask visual_hull_depth cameras.npz pointcloud.npz
```

**Comment by m-niemeyer** [comment]
Hi @nitish11,

yes, you are getting the error because you are not using a correct config file. The NMR Dataset you downloaded is only used by the RGB model which can be trained using [this config file](https://github.com/autonomousvision/differentiable_volumetric_rendering/blob/master/configs/single_view_reconstruction/multi_view_supervision/ours_rgb.yaml).

_img_folder_input_ is the name of the image folder; In the NMR Dataset, it is "image".

If you want to train the RGB model with on the category "03691459" from the NMR Dataset, you can add
```
  classes: ['02958343']
```
under `data` of [this config file](https://github.com/autonomousvision/differentiable_volumetric_rendering/blob/0918b64f9696f12dd595098b164de2388b3fbf4f/configs/single_view_reconstruction/multi_view_supervision/ours_rgb.yaml), but you have to keep the other options as they are. 

To be completely clear, you end up with a config file with the following config:
```
data:
  dataset_name: NMR
  path: data/NMR_Dataset
  train_split: softras_train
  val_split: softras_val
  test_split: softras_test
  img_folder_input: image
  img_extension_input: png
  depth_from_visual_hull: true
  depth_range: [0., 5.]
  classes: ['02958343']
model:
  decoder_kwargs:
    hidden_size: 128
training:
  out_dir:  out/single_view_reconstruction/multi_view_supervision/ours_rgb
  n_workers: 8
  model_selection_metric: mask_intersection
  model_selection_mode: maximize
  n_eval_points: 4096
```

Please check [this section of our readme](https://github.com/autonomousvision/differentiable_volumetric_rendering#training) for how to start training a model. I hope this helps!
