### ISSUE TITLE
How to test this on new image?

### ISSUE THREAD

**Issue by nitish11** [autonomousvision/differentiable_volumetric_rendering#19]
How to generate 3D model from a single 2D image?

The config  file mentioned below does't contain parameter test_input image path. https://github.com/autonomousvision/differentiable_volumetric_rendering/blob/master/configs/single_view_reconstruction/single_view_supervision/ours_combined_pretrained.yaml

Which part of the code generate 3D model, how to change the output format of 3D model?

**Comment by m-niemeyer** [comment]
Hi @nitish11 ,

if you only want to run our pretrained models on RGB images, [please have a look at our demo](https://github.com/autonomousvision/differentiable_volumetric_rendering#demo). You can further adjust the path to the image in [the respective demo config file](https://github.com/autonomousvision/differentiable_volumetric_rendering/blob/master/configs/demo/demo_combined.yaml#L4). Finally, in the [default config](https://github.com/autonomousvision/differentiable_volumetric_rendering/blob/master/configs/default.yaml#L88) you can find the config entry
```
generation:
  mesh_extension: ply
```
which you can use to change the output format

**Comment by nitish11** [comment]
Thanks @m-niemeyer for the hint. I was able to generate good quality of 3D models from random test images just by changing config file, configs/demo/demo_combined.yaml.  
```
inherit_from: configs/single_view_reconstruction/multi_view_supervision/ours_combined_pretrained.yaml
data:
  dataset_name: images
  path: media/test_images
training:
  out_dir:  media/out_3D_models
generation:
  generation_dir: generation
```

media/test_images : contains all the images
media/out_3D_models : contains all 3D models.
